version: '3'

services:
  stream-api:
    build: .
    image: asnelzin/stream-api
    container_name: "stream-api"
    hostname: "stream-api"
    restart: unless-stopped

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    ports:
      - "8080:8080"